server:
  port: 8182

spring:
  application:
    name: database #client will be registered under this name with eureka-server
  data:
    mongodb:
#      host:     ${MONGODB_HOST:localhost}
      host:     localhost
#      port:     ${MONGODB_PORT:27017}
      port:     27017
#      database: ${MONGODB_DBNAME:invisible}
      database: invisible
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
      enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/EurekaServer/eureka
#  instance:
#    hostname: localhosts