spring:
  application:
    name: auth

server:
  port: 8247


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/EurekaServer/eureka
#  instance:
#    hostname: localhosts