spring:
  application:
    name: web
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
#            filters:
        - id: database
          uri: http://localhost:8182/
          predicates:
            - Path=/database/**
          stripPrefix: false
#          filters:
#            - RewritePath=/database/(?.*), /$\{path}

server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/EurekaServer/eureka
#  instance:
#    hostname: localhosts