spring:
  application:
    name: web
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
#            filters:
        - id: database
          uri: lb://projectDB
          predicates:
            - Path=/database/**
#            filters:

server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/EurekaServer/eureka
#  instance:
#    hostname: localhosts