language: java
services:
- docker
addons:
  ssh_known_hosts: invisble.f4.htw-berlin.de
before_deploy:
- openssl aes-256-cbc -K $encrypted_6c8dcf28cc94_key -iv $encrypted_6c8dcf28cc94_iv
  -in travis_rsa.enc -out travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
  on:
    branch: master
