version: '3.3'
services:
  database:
    image: 'mongo'
    container-name: 'invisible'
    environment:
      - MONGO_INITDB_DATABASE=invisible
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'