version: '3.3'

networks:
  network-front:
    driver: bridge
  network-back:
    driver: bridge

volumes:
  da-data:

services:
  service-discovery:
    hostname: service-discovery
    build: ../service-discovery
    networks:
      - network-back
      - network-front
    ports:
      - "8761:8761"
    expose: 
      - "8761"
    environment: 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/EurekaServer/eureka
  database:
    build: ../database
    networks:
      - network-front
      - network-back
    links: 
      - service-discovery
    depends_on:
      - service-discovery
    environment: 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/EurekaServer/eureka
  web:
    build: ../web
    ports:
      - 8083:8083
    networks:
      - network-back
      - network-front
    links:
      - service-discovery
    depends_on:
      - service-discovery
    environment: 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/EurekaServer/eureka
