version: '3.3'

networks:
  network-front:
    driver: bridge
  network-back:
    driver: bridge

volumes:
  da-data:

services:
  service-discovery:
    build: ../service-discovery
    networks:
      - network-back
      - network-front
  database:
    build: ../database
    networks:
      - network-front
      - network-back
  web:
    build: ../web
    ports:
      - 8083:8083
    networks:
      - network-back
      - network-front
